sudo: required
language: node_js
node_js:
  - "node"
  - "8"

services:
  - docker

before_install:
  - docker-compose up -d
  - docker ps
  - sleep 10

script:
  - npm run build
  - npm run test:integration
